import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UploadProvider } from "./context/upload-provider";
import Header from "@/app/ui/header";
import Title from "@/app/ui/title";
import Hint from "@/app/ui/hint";
import History from "@/app/ui/history";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center flex-start p-20">
          <Header />
          <Title />
          <UploadProvider>{children}</UploadProvider>
          <Hint />
          <History />
        </main>
      </body>
    </html>
  );
}
